# Use postgres/example user/password credentials
version: '3.1'

services:

  otus-db-hw:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password # ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
