-- Warning: You can generate script only for one table/view at a time in your Free plan
--
-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Recipe book, v15 by pchelinanst@gmail.com ***


-- ************************************** dish.dish_tag

CREATE TABLE dish.dish_tag
(
    dish_id      bigint      NOT NULL,
    tag_id       bigint      NOT NULL,
    tag_name_rus varchar(50) NOT NULL,
    tag_name_eng varchar(50) NOT NULL,
    CONSTRAINT PK_1 PRIMARY KEY (dish_id, tag_id)
);

COMMENT ON TABLE dish.dish_tag IS 'Связь м-ду тегами и типами тегов';

COMMENT ON COLUMN dish.dish_tag.tag_name_rus IS '- категории (англ + рус)
    - Рецепты блюд по времени приема пищи: завтрак / обед / ужин / перекус / полдник

    - Рецепты по типу блюд: закуска / десерт / суп / первое блюдо / второе блюдо / напитки / гарнир / салат закуски выпечка , соусы и маринады , заготовки, ни т.п.

    - Рецепты с использованием: духовка / плита / микроволновка

    - Рецепты по способу приготовления блюд: выпекать / варить / жарить / тушить

    - Основа блюда: мясо / рыба  / овощи / птица / морепродукты / тесто

    - Рецепты блюд по событию: Новый год / Великий пост / Пасха / День благодарения

    - Другое: пп

Популярное: ....


Пицца
Шашлык
Блины
.....';




