-- Warning: You can generate script only for one table/view at a time in your Free plan
--
-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Recipe book, v15 by pchelinanst@gmail.com ***


-- ************************************** setting.dish_tag_type

CREATE TABLE settings.dish_tag_type
(
    tag_type_id bigint      NOT NULL,
    name_rus    varchar(50) NOT NULL,
    name_eng    varchar(50) NOT NULL,
    CONSTRAINT PK_1 PRIMARY KEY (tag_type_id)
);

COMMENT ON TABLE settings.dish_tag_type IS 'Настройки

Таблица с видами тегов

Примеры данных на русском:
- Рецепты по времени приготовления
- Рецепты по времени приема пищи
- Рецепты по типу блюд
- Рецепты по типу необходимого инвентаря
- Рецепты по способу приготовления блюд
- Основа блюда
- Рецепты блюд по событию
- Другое
- и др

В тэг "другое" пользователи смогут добавлять новые тэги для своих блюд, которых еще нет в таблице setting.dish_tag';





