-- Warning: You can generate script only for one table/view at a time in your Free plan
--
-- ************************* SqlDBM: PostgreSQL *************************
-- *** Generated by SqlDBM: Recipe book, v15 by pchelinanst@gmail.com ***


-- ************************************** setting.dish_and_tag

CREATE TABLE settings.dish_and_tag
(
    tag_type_id bigint NOT NULL,
    tag_id      bigint NOT NULL,
    CONSTRAINT PK_1 PRIMARY KEY (tag_type_id, tag_id)
);

COMMENT ON TABLE settings.dish_and_tag IS '- категории (англ + рус)
    - Рецепты блюд по времени приема пищи: завтрак / обед / ужин / перекус / полдник
    - Рецепты по типу блюд: закуска / десерт / суп / первое блюдо / второе блюдо / напитки / гарнир / салат и т.п.
    - Рецепты с использованием: духовка / плита / микроволновка
    - Рецепты по способу приготовления блюд: выпекать / варить / жарить / тушить

    - Основа блюда: мясо / рыба  / овощи / птица / морепродукты / тесто
    - Рецепты блюд по событию: Новый год / Великий пост / Пасха / День благодарения
    - Другое: пп


    - : мясо / рыба  / овощи / птица / морепродукты / тесто
    - : Новый год / Великий пост / Пасха / День благодарения
    - Другое: пп';





